name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./post/pom.xml
          mvn clean package -f ./offer/pom.xml
          mvn clean package -f ./deal/pom.xml
          mvn clean package -f ./mypage/pom.xml

      - name: Docker Build and push for Post
        uses: docker/build-push-action@v4
        with:
          context: ./post
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/post:latest
            ghcr.io/${{ github.repository }}/post:${{ github.ref_name }}
            
      - name: Docker Build and push for Offer
        uses: docker/build-push-action@v4
        with:
          context: ./offer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/offer:latest
            ghcr.io/${{ github.repository }}/offer:${{ github.ref_name }}
            
      - name: Docker Build and push for Deal
        uses: docker/build-push-action@v4
        with:
          context: ./deal
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/deal:latest
            ghcr.io/${{ github.repository }}/deal:${{ github.ref_name }}
            
      - name: Docker Build and push for Mypage
        uses: docker/build-push-action@v4
        with:
          context: ./mypage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mypage:latest
            ghcr.io/${{ github.repository }}/mypage:${{ github.ref_name }}
            
