server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: post
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**, 
        - id: offer
          uri: http://localhost:8083
          predicates:
            - Path=/offers/**, 
        - id: deal
          uri: http://localhost:8084
          predicates:
            - Path=/deals/**, 
        - id: mypage
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: post
          uri: http://post:8080
          predicates:
            - Path=/posts/**, 
        - id: offer
          uri: http://offer:8080
          predicates:
            - Path=/offers/**, 
        - id: deal
          uri: http://deal:8080
          predicates:
            - Path=/deals/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
